name: MeshLink
options:
  bundleIdPrefix: com.meshlink
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_FILE: MeshLink/Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: com.meshlink.app
    MARKETING_VERSION: "2.0.0"
    CURRENT_PROJECT_VERSION: "1"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    CODE_SIGN_STYLE: Automatic
    GENERATE_INFOPLIST_FILE: false
    ENABLE_BITCODE: false

targets:
  MeshLink:
    type: application
    platform: iOS
    sources:
      - path: MeshLink
    settings:
      base:
        PRODUCT_NAME: MeshLink
        INFOPLIST_FILE: MeshLink/Info.plist
    info:
      path: MeshLink/Info.plist
      properties:
        UIBackgroundModes:
          - bluetooth-central
          - bluetooth-peripheral
        NSBluetoothAlwaysUsageDescription: "MeshLink uses Bluetooth to find and connect to nearby peers for encrypted messaging."
        NSBluetoothPeripheralUsageDescription: "MeshLink uses Bluetooth to communicate with nearby peers."
